import argparse
import hashlib
import json
import runpy
from html.parser import HTMLParser
from pathlib import Path


class ReportLinks(HTMLParser):
    def __init__(self):
        super().__init__()
        self.targets = []

    def handle_starttag(self, tag, attributes):
        if tag == "a":
            self.targets.extend(value for name, value in attributes if name == "href" and value)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("review_directory", type=Path)
    args = parser.parse_args()
    root = args.review_directory
    inputs = ["semantic-first-batch-summary.json", "semantic-first-batch-register.json", "expected-code-1-review-register.json"]
    values = [json.loads((root / name).read_text(encoding="utf-8")) for name in inputs]
    summary, cases, queue = values
    assert len(cases) == summary["batchSize"] == 100
    assert len(queue) == summary["casesLinkedToScenarioExpectedCode1"] == 2005
    assert not summary["executionCertified"]
    data = {"summary": summary, "cases": cases, "queue": queue,
            "reportInputHashes": {name: hashlib.sha256((root / name).read_bytes()).hexdigest() for name in inputs}}
    controls_name = "semantic-bounded-control-pairs.json"
    data["controls"] = json.loads((root / controls_name).read_text(encoding="utf-8"))
    data["reportInputHashes"][controls_name] = hashlib.sha256((root / controls_name).read_bytes()).hexdigest()
    matrix_name = "late-traceability-matrix-assessment.json"
    matrix_section = ""
    matrix_tools = None
    autonomous_section = ""
    autonomous_name = "autonomous-qualification-assessment.json"
    if (root / autonomous_name).is_file():
        data["autonomousQualification"] = json.loads((root / autonomous_name).read_text(encoding="utf-8"))
        data["reportInputHashes"][autonomous_name] = hashlib.sha256((root / autonomous_name).read_bytes()).hexdigest()
        autonomous_section = runpy.run_path(str(Path(__file__).with_name("prepare-autonomous-cohort.py")))["report_section"](data["autonomousQualification"])
    if (root / matrix_name).is_file():
        matrix = json.loads((root / matrix_name).read_text(encoding="utf-8"))
        data["lateMatrix"] = {key: matrix[key] for key in ["intake", "producer", "independent", "history", "issues", "comparison", "requiredFollowUp", "disposition", "reconstruction", "supplementHistory"] if key in matrix}
        data["reportInputHashes"][matrix_name] = hashlib.sha256((root / matrix_name).read_bytes()).hexdigest()
        matrix_tools = runpy.run_path(str(Path(__file__).with_name("assess-late-traceability-matrix.py")))
        matrix_section = matrix_tools["report_section"](matrix)
    base = runpy.run_path(str(Path(__file__).with_name("generate-ai-artifact-filter-view.py")))["TEMPLATE"]
    style = base.split("<style>", 1)[1].split("</style>", 1)[0]
    style += EXTRA_STYLE
    encoded = json.dumps(data, ensure_ascii=True, separators=(",", ":")).replace("</", "<\\/")
    html = TEMPLATE.replace("__STYLE__", style).replace("__DATA__", encoded)
    if autonomous_section:
        html = html.replace('<section id="findings" role="tabpanel">', '<section id="findings" role="tabpanel">' + autonomous_section, 1)
        html = html.replace("No Java validator or host/converter execution result is claimed here.",
                            "No Java or host execution is claimed for the original 100-case bounded register. Separate autonomous cohort results are reported above.")
    if matrix_section:
        html = html.replace("</main>", '<section id="matrix-history" role="tabpanel" hidden>' + matrix_section + "</section></main>", 1)
        html = html.replace("['source','Source & provenance']", "['source','Source & provenance'],['matrix-history','Matrix & history']", 1)
    preserved = sum(count for state, count in summary["negativeMutationStates"].items() if state in {"DECLARED_VALUE_PRESERVED", "DECLARED_ABSENCE_PRESERVED"})
    blocked = summary["negativeMutationStates"].get("NOT_ASSESSED", 0)
    html = html.replace("18 / 25", f"{preserved} / 25")
    html = html.replace("7 remain unassessed", f"{blocked} {'remains' if blocked == 1 else 'remain'} unassessed")
    html = html.replace("18 mutation values preserved; 7 unassessed", f"{preserved} mutation/absence checks preserved; {blocked} unassessed")
    html = html.replace("Seven unassessed cases. The other 18 preserve declared mutation values but are not certified as effective negative tests.",
        "Six cases now have bounded physical evidence (four required absences, one maximum-length violation, one mapped enum mutation); one orphan case still needs an external processor oracle. None is certified as an effective negative test.")
    html = html.replace("Resolve composite mappings and mandatory-absence checks for the seven unassessed negatives.", "Verify application-specific negative objectives and resolve the remaining orphan processor oracle; six mapping/preservation blockers have bounded evidence.")
    html = html.replace("Mandatory-field absence is not yet evaluated by the bounded predicates. A composed orphan-follow-on case has no source-grounded processor outcome oracle. Composite rendering needs an explicit mapping, not field-name similarity.", "Four required-field omissions and two exact composite mappings are now assessed. These prove preservation, not isolated negative effectiveness. The orphan-follow-on outcome still requires processor rules, and the enum-negative objective needs application-specific evidence.")
    html = html.replace("First Semantic Assessment", "Bounded Semantic Assessment")
    html = html.replace('<a href="SEMANTIC-FIRST-BATCH-ASSESSMENT.md">Detailed assessment</a>', '<a href="SEMANTIC-FIRST-BATCH-ASSESSMENT.md">Initial assessment</a> &middot; <a href="BOUNDED-WORK-UPDATE.md">Latest bounded work</a>')
    detail_marker = "sourceContextCandidates:item.sourceContextCandidates,flowSequenceEvidence:item.flowSequenceEvidence,objectiveGate:item.objectiveGate"
    if html.count(detail_marker) != 1:
        raise RuntimeError("Case-detail template no longer has the expected objective evidence insertion point")
    html = html.replace(detail_marker, "objectiveEvidence:item.objectiveEvidence," + detail_marker, 1)
    blocker_loop = "for(const item of data.cases.filter(item=>item.intent==='negative'&&mutations(item).includes('NOT_ASSESSED'))){"
    if html.count(blocker_loop) != 1:
        raise RuntimeError("Negative blocker table template changed; refusing to publish a partial disposition view")
    html = html.replace(blocker_loop,
        "for(const disposition of data.summary.negativeBlockerAssessment.cases){const item=data.cases.find(caseRow=>caseRow.caseId===disposition.caseId);", 1)
    blocker_row = "row('blocker-body',['',item.negativeClass,item.violatedElement||'No field target',blocker(item)])"
    if html.count(blocker_row) != 1:
        raise RuntimeError("Negative blocker row template changed; refusing to publish a partial disposition view")
    html = html.replace(blocker_row,
        "row('blocker-body',['',item.negativeClass,item.violatedElement||'No field target',disposition.status])", 1)
    detail_summary = "'Mutation/absence evidence':data.summary.negativeMutationStates,'Code-1 physical context':data.summary.code1PhysicalContextStates"
    if html.count(detail_summary) != 1:
        raise RuntimeError("Summary detail template no longer has the expected evidence insertion point")
    html = html.replace(detail_summary,
        "'Mutation/absence evidence':data.summary.negativeMutationStates,'Seven negative dispositions':data.summary.negativeBlockerAssessment,'BR objective evidence':data.summary.brObjectiveEvidence,'Code-1 physical context':data.summary.code1PhysicalContextStates", 1)
    parsed_links = ReportLinks()
    parsed_links.feed(html)
    assert all((matrix_tools["native_path"](root / target) if matrix_tools else root / target).is_file() for target in parsed_links.targets)
    embedded = json.loads(html.split('<script type="application/json" id="data">', 1)[1].split("</script>", 1)[0])
    assert len(embedded["cases"]) == 100 and len(embedded["queue"]) == 2005
    assert all(hashlib.sha256((root / name).read_bytes()).hexdigest() == digest
               for name, digest in embedded["reportInputHashes"].items())
    output = root / "SEMANTIC-FIRST-BATCH-REPORT.html"
    output.write_text(html, encoding="utf-8")
    print(f"Generated {output}: 100 assessed cases, 2,005 outcome-review rows; hashes and links verified")


EXTRA_STYLE = """
.section-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.detail-table{width:100%;min-width:780px}.detail-table td{overflow-wrap:anywhere}.hash{font-family:Consolas,monospace;overflow-wrap:anywhere;font-size:12px}.meter{height:12px;background:#e3e9e7;max-width:240px;margin:7px 0}.meter span{display:block;height:100%;background:var(--amber)}.severity{font-size:12px;font-weight:700;color:var(--amber)}.ledger{margin-top:22px;border-top:2px solid var(--teal);padding-top:16px}.filters.small{grid-template-columns:minmax(200px,2fr) repeat(2,minmax(140px,1fr)) auto}.wrap-text{white-space:pre-wrap;overflow-wrap:anywhere}.source-table td{overflow-wrap:anywhere}.case-table th:nth-child(3){width:90px}.case-table th:nth-child(5){width:180px}.case-table th:nth-child(6){width:150px}.queue-table th:nth-child(3){width:260px}.queue-table th:nth-child(4){width:170px}.queue-table th:nth-child(5){width:180px}.queue-table th:nth-child(6){width:110px}
@media(max-width:850px){.filters.small{grid-template-columns:repeat(2,minmax(0,1fr))}.filters.small .field:first-child{grid-column:1/-1}.section-title{align-items:flex-start;flex-wrap:wrap}}
@media(max-width:500px){.filters.small{grid-template-columns:minmax(0,1fr)}.filters.small .field:first-child{grid-column:auto}}
@media print{nav,.filters,.pager,.actions,button{display:none!important}main>section[role=tabpanel]{display:block!important;break-before:page}#case-evidence{display:block}.register{min-width:0}.table-wrap{overflow:visible}body{font-size:10px}.source-table .hash{font-size:9px}}
"""


TEMPLATE = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATL105 | First Semantic Assessment</title><style>__STYLE__</style></head><body>
<header><div class="headline"><div><div class="metadata">CORE AUTH / ATL105 2026-3 / OCTOBER 5 RUN1 SUPPLEMENT</div><h1>First Semantic Assessment</h1><div class="metadata">October 6, 2026 &middot; 100-case deterministic batch &middot; <span class="badge">REVIEW REQUIRED</span></div></div><div class="actions"><button id="print-report" class="icon" title="Print report" aria-label="Print report">&#9113;</button><a class="command" href="AI-ARTIFACT-FILTER-VIEW.html">Run assessment</a></div></div></header>
<nav role="tablist" aria-label="Semantic assessment sections"></nav>
<main>
<section id="findings" role="tabpanel"><div class="metrics"><div class="metric"><span>ASSESSED CASES</span><strong>100</strong><span>25 per intent; not a random sample</span></div><div class="metric"><span>INTERPRETED PHYSICAL LEGS</span><strong>131</strong><span>Explicit metadata paths only</span></div><div class="metric"><span>NEGATIVE MUTATIONS PRESERVED</span><strong>18 / 25</strong><span>7 remain unassessed</span></div><div class="metric"><span>SEMANTIC CERTIFICATION</span><strong style="font-size:22px;color:var(--amber)">Not established</strong><span>Independent coverage: not calculable</span></div></div>
<div class="notice">Shared BR IDs, preserved mutations and passing field predicates do not establish complete BR equivalence or negative-test effectiveness. All 100 cases remain REVIEW_REQUIRED. No run-wide defect rate can be inferred from this deterministic batch.</div>
<div class="two-col"><div><h2>Recommended-order findings</h2><table class="plain-table"><thead><tr><th>Stage</th><th>Observed evidence</th><th>Remaining gate</th></tr></thead><tbody><tr><td>1. Interpretation</td><td>131 payload/metadata legs joined</td><td>Full producer-format adapter not certified</td></tr><tr><td>2. BR objective alignment</td><td>75 cases share BR IDs; 25 sampled flows do not</td><td>Shared IDs are not behavioral equivalence</td></tr><tr><td>3. Negative effectiveness</td><td>18 mutation values preserved; 7 unassessed</td><td>Isolated valid control and outcome oracle</td></tr><tr><td>4. Expected outcomes</td><td>All 21,123 TC expected responses empty; 2,005 code-1 review rows</td><td>Source-backed family and expected behavior</td></tr><tr><td>5. Source/payload checks</td><td>259 passing field observations; 2 intentional invalid inputs</td><td>Broader segment, wire and lifecycle checks</td></tr></tbody></table></div>
<div><h2>Narrow source observations</h2><table class="plain-table"><thead><tr><th>Measure</th><th class="number">Count</th></tr></thead><tbody><tr><td>Field-predicate observations</td><td class="number">261</td></tr><tr><td>Passing field observations (not passing tests)</td><td class="number">259</td></tr><tr><td>Intentional negative predicate failures</td><td class="number">2</td></tr><tr><td>Unexpected failures in these predicates</td><td class="number">0</td></tr></tbody></table><div class="notice">TC-002869 uses Segment Type 000; TC-002970 uses 101 instead of source-fixed 100. These are intended negative inputs, not independently identified AI defects. Zero unexpected failures does not establish a zero false-pass rate.</div></div></div>
<div class="band"><h2>Potential confounders</h2><table class="plain-table"><thead><tr><th>Producer method</th><th class="number">Selected cases</th><th>Meaning</th></tr></thead><tbody id="confounders"></tbody></table><p class="scope">Populations overlap. These methods identify unresolved-state risks, not automatic business defects. A negative test can be obscured by unrelated failures unless the surrounding baseline is validated.</p></div>
<div class="band"><h2>Next bounded work</h2><ol><li>Resolve composite mappings and mandatory-absence checks for the seven unassessed negatives.</li><li>Establish source/context support for BR objectives and missing flow BR links.</li><li>Use valid control fixtures and paired mutations; record intended-rule detection separately from unrelated errors.</li><li>Adjudicate response-family and expected-outcome evidence for code-1 candidates without inventing host responses.</li><li>Expand supported segment, compatibility, serialization and lifecycle validators.</li></ol></div></section>
<section id="cases" role="tabpanel" hidden><h2>100-case assessment register</h2><div class="filters small"><div class="field"><label for="case-search">TC / scenario / BR / statement</label><input id="case-search" type="search" placeholder="TC-002869 or source rule"></div><div class="field"><label for="case-intent">Intent</label><select id="case-intent"></select></div><div class="field"><label for="case-condition">Assessment condition</label><select id="case-condition"></select></div><button class="icon" id="case-reset" title="Reset case filters" aria-label="Reset case filters">&#8634;</button></div><div class="results-heading"><span id="case-count" aria-live="polite"></span><button class="command" id="case-csv">&#8595; Selected CSV</button></div><div class="table-wrap"><table class="register case-table"><thead><tr><th>Case / scenario</th><th>Intent</th><th>Shared BRs</th><th>Field observations</th><th>Mutation status</th><th>Disposition</th></tr></thead><tbody id="case-body"></tbody></table></div><section id="case-evidence" class="evidence" hidden></section></section>
<section id="negatives" role="tabpanel" hidden><h2>Negative-test blockers</h2><p class="scope">Seven unassessed cases. The other 18 preserve declared mutation values but are not certified as effective negative tests.</p><div class="table-wrap"><table class="plain-table detail-table"><thead><tr><th>Case</th><th>Negative class</th><th>Target</th><th>Assessment blocker</th></tr></thead><tbody id="blocker-body"></tbody></table></div><div class="band"><h2>Mutation-class selection</h2><table class="plain-table"><thead><tr><th>Class</th><th class="number">Selected cases</th></tr></thead><tbody id="negative-classes"></tbody></table></div><div class="notice">Mandatory-field absence is not yet evaluated by the bounded predicates. A composed orphan-follow-on case has no source-grounded processor outcome oracle. Composite rendering needs an explicit mapping, not field-name similarity.</div></section>
<section id="outcomes" role="tabpanel" hidden><h2>Expected-code-1 review queue</h2><p class="scope">2,005 TCs linked to scenarios declaring code 1. Their TC expected responses are empty. Financial decline versus Communications Test approval semantics must not be inferred from an unverified message-family label.</p><div class="filters small"><div class="field"><label for="queue-search">TC / scenario / source rule</label><input id="queue-search" type="search" placeholder="TC or scenario ID"></div><div class="field"><label for="queue-family">Producer transaction label</label><select id="queue-family"></select></div><div class="field"><label for="queue-source">Source evidence</label><select id="queue-source"></select></div><button class="icon" id="queue-reset" title="Reset outcome filters" aria-label="Reset outcome filters">&#8634;</button></div><div class="results-heading"><span id="queue-count" aria-live="polite"></span><button class="command" id="queue-csv">&#8595; Selected CSV</button></div><div class="table-wrap"><table class="register queue-table"><thead><tr><th>Case</th><th>Scenario</th><th>Producer transaction label</th><th>Source rule / page</th><th>Expected outcome</th><th>Disposition</th></tr></thead><tbody id="queue-body"></tbody></table></div><div class="pager"><button class="icon" id="queue-previous" title="Previous queue page" aria-label="Previous queue page">&#8592;</button><span id="queue-page"></span><button class="icon" id="queue-next" title="Next queue page" aria-label="Next queue page">&#8594;</button></div></section>
<section id="source" role="tabpanel" hidden><h2>Source predicates and provenance</h2><table class="plain-table source-table"><thead><tr><th>Element / section</th><th>Literal source quote</th><th>Bounded assertion</th></tr></thead><tbody id="source-predicates"></tbody></table><div class="notice">Six ASCII digits do not prove Sequence Number allocation, the full allowed range, or lifecycle correlation. Segment 100 identity does not validate every required field, wire length or transaction context. No Java validator or host/converter execution result is claimed here.</div><div class="band"><h2>Deterministic selection</h2><p class="scope" id="selection"></p><table class="plain-table"><thead><tr><th>Intent</th><th class="number">Cases</th></tr></thead><tbody id="strata"></tbody></table></div><div class="band"><h2>Input SHA-256 hashes</h2><table class="plain-table source-table"><thead><tr><th>Artifact</th><th>SHA-256</th></tr></thead><tbody id="input-hashes"></tbody></table><h3>Report-data hashes</h3><table class="plain-table source-table"><thead><tr><th>Derived evidence</th><th>SHA-256</th></tr></thead><tbody id="report-hashes"></tbody></table></div></section>
</main><footer>REVIEW REQUIRED &middot; No producer input or approval state modified &middot; <a href="SEMANTIC-FIRST-BATCH-ASSESSMENT.md">Detailed assessment</a> &middot; <a href="semantic-first-batch-register.csv">100-case CSV</a> &middot; <a href="expected-code-1-review-register.csv">Complete outcome queue CSV</a> &middot; <a href="semantic-first-batch-summary.json">Evidence summary</a></footer>
<script type="application/json" id="data">__DATA__</script><script>
'use strict';const data=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id);let queuePage=0,currentCases=[],currentQueue=[];
function textCell(tr,text,cls){const td=document.createElement('td');td.textContent=text??'Not declared';if(cls)td.className=cls;tr.append(td);return td}
function row(id,values){const tr=document.createElement('tr');values.forEach(value=>textCell(tr,value));$(id).append(tr);return tr}
function options(id,values){$(id).replaceChildren(...values.map(([value,label])=>new Option(label,value)))}
function mutations(item){return [...new Set(item.physicalLegs.map(leg=>leg.negativeMutation))].join(', ')}
function blocker(item){return item.physicalLegs.map(leg=>leg.unassessedReason).filter(Boolean).join(', ')}
for(const [id,label]of [['findings','Executive findings'],['cases','Case register'],['negatives','Negative blockers'],['outcomes','Code-1 review queue'],['source','Source & provenance']]){const button=document.createElement('button');button.textContent=label;button.dataset.view=id;button.setAttribute('role','tab');button.setAttribute('aria-controls',id);button.setAttribute('aria-selected',String(id==='findings'));button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(other=>{const selected=other===button;other.setAttribute('aria-selected',String(selected));$(other.dataset.view).hidden=!selected})};document.querySelector('nav').append(button)}
options('case-intent',[['','All intents'],...Object.keys(data.summary.strata).map(value=>[value,value])]);options('case-condition',[['','All conditions'],['blocked','Unassessed negative mutation'],['no-br','No shared BR IDs'],['failure','Source-predicate failure observed'],['negative','All negative cases']]);options('queue-family',[['','All producer labels'],...Object.keys(data.summary.code1QueueTransactionLabels).map(value=>[value,value])]);options('queue-source',[['','All evidence'],['page','Missing source page'],['rule','Missing source rule']]);
options('queue-source',[['','All evidence'],['page','Missing source page'],['rule','Missing source rule'],['context','Exact-heading context candidate'],['alias','Unresolved producer alias'],['output','No physical output reference'],['matrix','Review-matrix/source concern']]);
function renderCases(){const query=$('case-search').value.trim().toLowerCase(),intent=$('case-intent').value,condition=$('case-condition').value;currentCases=data.cases.filter(item=>{const matches=!condition||condition==='blocked'&&item.intent==='negative'&&mutations(item).includes('NOT_ASSESSED')||condition==='no-br'&&!item.sharedBrIds.length||condition==='failure'&&item.sourcePredicateFailures>0||condition==='negative'&&item.intent==='negative';const searchable=[item.caseId,item.scenarioId,item.scenarioName,...item.caseBrIds,...item.linkedBrStatements.map(br=>br.statement+' '+br.sourceRule)].join(' ').toLowerCase();return (!query||searchable.includes(query))&&(!intent||item.intent===intent)&&matches});$('case-count').textContent=currentCases.length+' selected / 100 assessed cases';$('case-csv').disabled=!currentCases.length;$('case-body').replaceChildren();for(const item of currentCases){const tr=document.createElement('tr'),td=textCell(tr,'');const button=document.createElement('button');button.className='row-link';button.textContent=item.caseId;button.onclick=()=>showCase(item);td.append(button);const scenario=document.createElement('span');scenario.className='sub';scenario.textContent=item.scenarioId;td.append(scenario);textCell(tr,item.intent);textCell(tr,item.sharedBrIds.length);textCell(tr,item.sourcePredicatePasses+' pass / '+item.sourcePredicateFailures+' fail');textCell(tr,mutations(item));textCell(tr,item.overallDisposition,'severity');$('case-body').append(tr)}if(!currentCases.length){const tr=row('case-body',['No cases match the selected criteria']);tr.firstChild.colSpan=6}}
function showCase(item){const panel=$('case-evidence');panel.replaceChildren();panel.hidden=false;const heading=document.createElement('h2');heading.textContent=item.caseId+' / '+item.intent;panel.append(heading);const dl=document.createElement('dl');for(const [name,value]of Object.entries({'Scenario':item.scenarioName,'Producer transaction label':item.transactionLabel,'Semantic alignment':item.semanticAlignment,'Case BR IDs':item.caseBrIds.join(', ')||'None','Scenario BR IDs':item.scenarioBrIds.join(', ')||'None','Shared BR IDs':item.sharedBrIds.join(', ')||'None','Scenario BRs not referenced':item.scenarioBrsNotReferencedByCase.join(', ')||'None','Case BRs not declared by scenario':item.caseBrsNotDeclaredByScenario.join(', ')||'None','Negative class / target':(item.negativeClass||'Not applicable')+' / '+(item.violatedElement||'Not declared'),'Negative effectiveness':item.negativeEffectiveness,'Scenario expected code':item.scenarioExpectedCode??'Not declared','TC expected response':JSON.stringify(item.caseExpectedResponse),'Potential confounders':JSON.stringify(item.potentialConfounders,null,2)})){const dt=document.createElement('dt');dt.textContent=name;const dd=document.createElement('dd');dd.textContent=value;dl.append(dt,dd)}panel.append(dl);const brTitle=document.createElement('h3');brTitle.textContent='Linked BR source claims';panel.append(brTitle);for(const br of item.linkedBrStatements){const p=document.createElement('p');p.className='scope';p.textContent=br.id+' | '+br.statement+' | '+(br.sourceRule||'No rule')+' / '+(br.sourcePage??'No page');panel.append(p)}for(const leg of item.physicalLegs){const title=document.createElement('h3');title.textContent=leg.file+' / '+leg.interpretation;panel.append(title);const status=document.createElement('p');status.className='scope';status.textContent='Mutation: '+leg.negativeMutation+' | Blocker: '+(leg.unassessedReason||'None recorded');panel.append(status);const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Field observations, mutation checks and hashes';const pre=document.createElement('pre');pre.className='wrap-text';pre.textContent=JSON.stringify({fieldChecks:leg.fieldChecks,mutationChecks:leg.mutationChecks,payloadSha256:leg.payloadSha256,metadataSha256:leg.metadataSha256},null,2);details.append(summary,pre);panel.append(details)}panel.scrollIntoView({behavior:'smooth',block:'start'})}
function renderQueue(){
const query=$('queue-search').value.trim().toLowerCase(),family=$('queue-family').value,source=$('queue-source').value;
currentQueue=data.queue.filter(item=>{const state=item.physicalContextEvidence?.status;const sourceMatch=!source||source==='page'&&item.sourcePage==null||source==='rule'&&!item.sourceRuleId||source==='context'&&state==='EXACT_SOURCE_HEADING_CONTEXT_CANDIDATE'||source==='alias'&&state==='PRODUCER_ALIAS_CONTEXT_UNRESOLVED'||source==='output'&&state==='NO_PHYSICAL_OUTPUT_REFERENCE'||source==='matrix'&&item.physicalContextEvidence?.reviewMatrixPairStatus==='NOT_LISTED_IN_REVIEW_MATRIX_SOURCE_ADJUDICATION_REQUIRED';return (!query||[item.caseId,item.scenarioId,item.sourceRuleId,...item.requirementIds].join(' ').toLowerCase().includes(query))&&(!family||item.transactionLabel===family)&&sourceMatch});
const pages=Math.max(1,Math.ceil(currentQueue.length/50));queuePage=Math.min(queuePage,pages-1);$('queue-count').textContent=currentQueue.length.toLocaleString()+' selected / 2,005 outcome-review candidates';$('queue-page').textContent='Page '+(queuePage+1)+' of '+pages;$('queue-previous').disabled=queuePage===0;$('queue-next').disabled=queuePage>=pages-1;$('queue-csv').disabled=!currentQueue.length;$('queue-body').replaceChildren();
for(const item of currentQueue.slice(queuePage*50,(queuePage+1)*50)){const tr=row('queue-body',[item.caseId,item.scenarioId,item.transactionLabel,(item.sourceRuleId||'No rule')+' / '+(item.sourcePage??'No page'),item.expectedOutcomeDisposition,item.independentDisposition]);const note=document.createElement('span');note.className='sub';note.textContent=(item.physicalContextEvidence?.status||'NOT_ASSESSED')+' / '+(item.physicalContextEvidence?.family||'Unresolved family');tr.children[2].append(note)}
if(!currentQueue.length){const tr=row('queue-body',['No outcome candidates match']);tr.firstChild.colSpan=6}}
function exportCsv(items,fields,filename){const quote=value=>{let text=Array.isArray(value)?value.join('; '):String(value??'');if(/^[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'};const csv='\ufeff'+[fields.map(quote).join(','),...items.map(item=>fields.map(field=>quote(item[field])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const originalShowCase=showCase;showCase=item=>{originalShowCase(item);const context=document.createElement('pre');context.className='wrap-text';context.textContent=JSON.stringify({sourceContextCandidates:item.sourceContextCandidates,flowSequenceEvidence:item.flowSequenceEvidence,objectiveGate:item.objectiveGate},null,2);$('case-evidence').append(context)};
for(const id of ['case-search','case-intent','case-condition'])$(id).addEventListener(id==='case-search'?'input':'change',()=>{$('case-evidence').hidden=true;renderCases()});for(const id of ['queue-search','queue-family','queue-source'])$(id).addEventListener(id==='queue-search'?'input':'change',()=>{queuePage=0;renderQueue()});$('case-reset').onclick=()=>{for(const id of ['case-search','case-intent','case-condition'])$(id).value='';$('case-evidence').hidden=true;renderCases()};$('queue-reset').onclick=()=>{for(const id of ['queue-search','queue-family','queue-source'])$(id).value='';queuePage=0;renderQueue()};$('queue-previous').onclick=()=>{queuePage--;renderQueue()};$('queue-next').onclick=()=>{queuePage++;renderQueue()};$('case-csv').onclick=()=>exportCsv(currentCases,['caseId','scenarioId','intent','negativeClass','violatedElement','sharedBrIds','sourcePredicatePasses','sourcePredicateFailures','semanticAlignment','overallDisposition'],'selected-semantic-cases.csv');$('queue-csv').onclick=()=>exportCsv(currentQueue,['caseId','scenarioId','intent','transactionLabel','sourceRuleId','sourcePage','scenarioExpectedCode','expectedOutcomeDisposition','independentDisposition'],'selected-code-1-review.csv');$('print-report').onclick=()=>window.print();
for(const [method,count]of Object.entries(data.summary.batchConfounderCases)){const tr=row('confounders',[method,count,'Unresolved-state signal; not an automatic defect']);const meter=document.createElement('div');meter.className='meter';const bar=document.createElement('span');bar.style.width=count+'%';meter.append(bar);tr.firstChild.append(meter)}
for(const item of data.cases.filter(item=>item.intent==='negative'&&mutations(item).includes('NOT_ASSESSED'))){const tr=row('blocker-body',['',item.negativeClass,item.violatedElement||'No field target',blocker(item)]);const button=document.createElement('button');button.className='row-link';button.textContent=item.caseId;button.onclick=()=>{document.querySelector('[data-view="cases"]').click();showCase(item)};tr.firstChild.append(button)}
const update=document.createElement('section');update.className='band';const updateTitle=document.createElement('h2');updateTitle.textContent='Latest bounded work';update.append(updateTitle);for(const [name,value]of Object.entries({'Mutation/absence evidence':data.summary.negativeMutationStates,'Code-1 physical context':data.summary.code1PhysicalContextStates,'Flow sequence observations':data.summary.flowSequenceStates,'Remaining gates':data.summary.remainingGates,'Predicate control scope':data.summary.controlScope})){const title=document.createElement('h3');title.textContent=name;const content=document.createElement('pre');content.className='wrap-text';content.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);update.append(title,content)}$('findings').append(update);
const sourceUpdate=document.createElement('pre');sourceUpdate.className='wrap-text';sourceUpdate.textContent=JSON.stringify({expandedSourceGates:data.summary.expandedSourceGates,boundedControls:data.controls},null,2);$('source').append(sourceUpdate);
const matrixNotice=document.createElement('div');matrixNotice.className='notice';matrixNotice.textContent=data.summary.code1ReviewMatrixConcerns+' context candidates are not listed for code 1 in the review-status matrix. The source has a broader non-communications decline clause; source/matrix disagreement remains review-required, not an invalidity or acceptance verdict.';$('outcomes').prepend(matrixNotice);
for(const [name,count]of Object.entries(data.summary.negativeClasses))row('negative-classes',[name,count]);for(const predicate of data.summary.sourcePredicates)row('source-predicates',[predicate.element+' / '+predicate.section,predicate.quote,predicate.scope]);$('selection').textContent=data.summary.selection+'. Non-random; no defect-rate inference.';for(const [name,count]of Object.entries(data.summary.strata))row('strata',[name,count]);for(const [name,hash]of Object.entries(data.summary.inputSha256)){const tr=row('input-hashes',[name,hash]);tr.lastChild.className='hash'}for(const [name,hash]of Object.entries(data.reportInputHashes)){const tr=row('report-hashes',[name,hash]);tr.lastChild.className='hash'}renderCases();renderQueue();
</script></body></html>'''


if __name__ == "__main__":
    main()