import argparse
import csv
import hashlib
import json
import os
from collections import defaultdict
from pathlib import Path


def native(path):
    path = Path(os.path.normpath(str(path)))
    if os.name == "nt" and not str(path).startswith("\\\\?\\"):
        return Path("\\\\?\\" + str(path.resolve()))
    return path


def read(path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def source_evidence(elements, anchor):
    results = []
    values = str(anchor.get("element") or "").split(",")
    wanted_section = str(anchor.get("section") or "").strip().casefold()
    for value in values:
        element_id = value.strip()
        if not element_id or element_id not in elements:
            continue
        element = elements[element_id]
        definitions = element.get("definitions") or []
        exact = [item for item in definitions
                 if str(item.get("sourceSection") or "").strip().casefold() == wanted_section]
        selected = exact or definitions
        results.append({
            "element": element_id,
            "elementInventoryStatus": element.get("status"),
            "sectionMatchedExactly": bool(exact),
            "definitions": [{
                "sourceSection": item.get("sourceSection"),
                "sourceLine": item.get("sourceLine"),
                "sourceText": item.get("sourceText"),
                "constraints": item.get("constraints"),
            } for item in selected],
        })
    return results


def build_packet(analysis_dir, test_solution_dir):
    analysis_dir = native(analysis_dir)
    test_solution_dir = native(test_solution_dir)
    source_dir = test_solution_dir.parents[1] / "docs/specs/kb"
    crosswalk_dir = analysis_dir / "run4-independent-br-crosswalk-v2"
    crosswalk_summary = read(crosswalk_dir / "run4-ai-br-chain-crosswalk-summary.json")
    baseline_path = test_solution_dir / "source-derived-requirement-inventory.json"
    classification_path = test_solution_dir / "atomic-composite-rule-classification.json"
    element_inventory_path = test_solution_dir / "all-element-inventory.json"
    baseline = read(baseline_path)
    classification = read(classification_path)
    element_inventory = read(element_inventory_path)
    ai_elements = element_inventory.get("elements", {})
    rules_by_id = {rule["ruleId"]: rule for rule in classification["rules"]}
    catalog_cache = {}

    if baseline.get("authority") != "INDEPENDENT_TEST_SOLUTION" or baseline.get("aiArtifactsIncluded") is not False:
        raise ValueError("Independent Test Solution inventory provenance is invalid")
    if baseline.get("ruleCount") != 601 or len(baseline["businessRequirements"]) != 601:
        raise ValueError("Expected the verified 601-rule Test Solution baseline")
    if crosswalk_summary["aiBusinessRequirementCount"] != 5153:
        raise ValueError("Expected complete 5,153-BR Run4 crosswalk")
    if crosswalk_summary["run4ConfirmedSemanticMatches"] != 0:
        raise ValueError("Run4 semantic decisions must be reviewed, not generated by this packet builder")

    def test_rule_record(rule):
        relative = str(rule.get("sourceCatalog") or "")
        catalog_path = native(source_dir / relative)
        try:
            catalog_path.relative_to(native(source_dir))
        except ValueError as exc:
            raise ValueError("Test Solution catalog path escapes the approved KB root") from exc
        if relative not in catalog_cache:
            catalog = read(catalog_path)
            catalog_cache[relative] = {item.get("ruleId"): item for item in catalog.get("rules", [])}
        record = catalog_cache[relative].get(rule["ruleId"])
        if record is None:
            raise ValueError("Independent BR missing from its source catalog: " + rule["ruleId"])
        return record, relative

    ai_rows_by_test_rule = defaultdict(list)
    ai_rows = []
    crosswalk_path = crosswalk_dir / "run4-ai-br-chain-crosswalk.jsonl"
    with crosswalk_path.open("r", encoding="utf-8") as stream:
        for line in stream:
            ai_row = json.loads(line)
            ai_rows.append(ai_row)
            for candidate in ai_row.get("testSolutionRuleCandidates", []):
                rule_id = candidate["ruleId"]
                if rule_id not in rules_by_id:
                    raise ValueError("Candidate references unknown Test Solution BR: " + rule_id)
                pair = {
                    "delivery": crosswalk_summary["delivery"],
                    "reviewStatus": "PENDING_SEMANTIC_REVIEW",
                    "decision": None,
                    "reviewer": None,
                    "rationale": None,
                    "reviewId": ai_row["aiRequirementId"] + "::" + rule_id,
                    "matchSegment": None,
                    "aiRequirement": {
                        "id": ai_row["aiRequirementId"],
                        "statement": ai_row["aiStatement"],
                        "sourceRuleId": ai_row.get("aiSourceRuleId"),
                        "sourcePage": ai_row.get("aiSourcePage"),
                        "segmentNumber": ai_row.get("aiSegmentNumber"),
                        "segmentIds": ai_row.get("aiSegmentIds", []),
                        "derivationMethod": ai_row.get("aiDerivationMethod"),
                        "approvalFiltered": False,
                        "sourceAnchorCandidateStatus": ai_row["sourceAnchorCandidateStatus"],
                        "sourceEvidence": source_evidence(ai_elements, {"element": ai_row.get("inferredElement")}),
                    },
                    "testSolutionRequirement": {
                        **candidate,
                        "sourceCatalogPath": "docs/specs/kb/" + str(candidate["sourceCatalog"]),
                        "catalogRule": None,
                        "atl105SourceEvidence": source_evidence(ai_elements, candidate.get("sourceAnchor") or {}),
                    },
                    "chainEvidence": ai_row.get("matrixAndDirectChain", {}),
                    "requiredReview": [
                        "Compare normative behavior and conditions, not just element/segment identity.",
                        "Verify the AI source page and Test Rule source anchor against ATL105 2026-3 evidence.",
                        "Check whether the AI BR is equivalent, partial, composite, conflicting, duplicate, or unrelated.",
                        "Do not decide from the producer's approval, confidence, matrix status, or this candidate ranking.",
                    ],
                    "allowedDecision": ["CONFIRMED_MATCH", "DUPLICATE", "NEW_RULE", "REJECT", "REVIEW_REQUIRED"],
                }
                test_segments = {value.strip().upper() for value in str((candidate.get("sourceAnchor") or {}).get("segment") or "").split(",") if value.strip()}
                pair["matchSegment"] = next((value for value in ai_row.get("candidateSegments", [])
                                              if str(value).upper() in test_segments), None)
                if not pair["matchSegment"]:
                    raise ValueError("Candidate pair has no shared normalized segment: " + pair["reviewId"])
                ai_rows_by_test_rule[rule_id].append(pair)

    for rule_id, pairs in ai_rows_by_test_rule.items():
        rule = rules_by_id[rule_id]
        record, relative = test_rule_record(rule)
        for pair in pairs:
            pair["testSolutionRequirement"]["catalogRule"] = record
            pair["testSolutionRequirement"]["sourceCatalogPath"] = "docs/specs/kb/" + relative

    test_rule_reviews = []
    for rule in baseline["businessRequirements"]:
        rule_id = rule["ruleId"]
        classification_rule = rules_by_id[rule_id]
        record, relative = test_rule_record(rule)
        pairs = ai_rows_by_test_rule.get(rule_id, [])
        test_rule_reviews.append({
            "delivery": crosswalk_summary["delivery"],
            "testRuleId": rule_id,
            "reviewStatus": "PENDING_SEMANTIC_REVIEW",
            "decision": None,
            "reviewer": None,
            "rationale": None,
            "testSolutionRequirement": {
                **rule,
                "atomicity": classification_rule.get("atomicity"),
                "sourceCatalogPath": "docs/specs/kb/" + relative,
                "catalogRule": record,
                "atl105SourceEvidence": source_evidence(ai_elements, rule.get("sourceAnchor") or {}),
            },
            "anchorCandidateCount": len(pairs),
            "anchorCandidates": pairs,
            "manualAiCorpusSearchRequired": not bool(pairs),
            "noMatchConclusionAllowed": False,
            "coverageCredit": False,
        })

    pair_count = sum(len(items) for items in ai_rows_by_test_rule.values())
    decision_register = {
        "artifact": "test-solution-sme-decision-register",
        "version": "1.0",
        "authority": "TEST_SOLUTION_REVIEW",
        "delivery": crosswalk_summary["delivery"],
        "registerScope": "Run4 AI-to-Test candidate pairs only; this register is separate from the historical Run2 register.",
        "policy": "Every seed is PENDING. Append a reviewer decision only after source-backed semantic adjudication. Pending or unreviewed records never count as coverage.",
        "decisionStatuses": ["PENDING", "NEW_RULE", "DUPLICATE", "REJECT", "CONFIRMED_MATCH", "REVIEW_REQUIRED"],
        "subjectTypes": ["AI_TO_TEST_CROSSWALK"],
        "decisions": [],
    }
    for rule_id in sorted(ai_rows_by_test_rule):
        for pair in ai_rows_by_test_rule[rule_id]:
            identity = pair["reviewId"]
            digest = hashlib.sha256(identity.encode("utf-8")).hexdigest()[:16]
            decision_register["decisions"].append({
                "decisionId": "RUN4-PENDING-" + digest,
                "subjectType": "AI_TO_TEST_CROSSWALK",
                "subjectId": identity,
                "segment": pair["matchSegment"],
                "decision": "PENDING",
                "reviewer": "UNREVIEWED",
                "rationale": "Awaiting authorized Test SME semantic review of this AI BR/Test BR pair.",
                "evidence": [{
                    "type": "RUN4_SEMANTIC_REVIEW_PACKET_PAIR",
                    "path": "run4-ai-test-br-semantic-review-pairs.jsonl",
                    "reviewId": identity,
                    "aiRequirementId": pair["aiRequirement"]["id"],
                    "testRuleId": pair["testSolutionRequirement"]["ruleId"],
                }],
            })
    summary = {
        "artifact": "ATL105-RUN4-SOURCE-BACKED-SEMANTIC-REVIEW-PACKET",
        "delivery": crosswalk_summary["delivery"],
        "reviewAuthority": "AUTHORIZED_TEST_SME_OR_DELEGATED_TEST_SOLUTION_REVIEWER",
        "aiApprovalFilterApplied": False,
        "independentTestSolutionBrCount": len(test_rule_reviews),
        "aiBrCount": len(ai_rows),
        "candidatePairCount": pair_count,
        "pendingPairDecisionCount": len(decision_register["decisions"]),
        "independentTestRulesWithAnchorCandidates": sum(bool(items) for items in ai_rows_by_test_rule.values()),
        "independentTestRulesRequiringManualAiCorpusSearch": len(test_rule_reviews) - sum(bool(items) for items in ai_rows_by_test_rule.values()),
        "confirmedMatches": 0,
        "coverageStatus": "NOT_ASSESSED",
        "coverageCreditIssued": False,
        "sourceEvidenceSha256": element_inventory.get("sourceSha256"),
        "independentBaselineSha256": sha256(baseline_path),
        "atomicityClassificationSha256": sha256(classification_path),
        "run4CrosswalkSummarySha256": sha256(crosswalk_dir / "run4-ai-br-chain-crosswalk-summary.json"),
        "policy": "Source excerpts and structural candidates are review evidence only. Semantic decisions require a named authorized reviewer, rationale, validated source anchor, and an append-only Run4-bound decision event. No automated confirmation or coverage credit is produced.",
    }
    return summary, test_rule_reviews, ai_rows_by_test_rule, decision_register


def self_test():
    elements = {"4": {"status": "SOURCE_REVIEW_REQUIRED", "definitions": [
        {"sourceSection": "13.2", "sourceLine": 10, "sourceText": "positions 1-12 city; 13 space", "constraints": {"lengthMode": "FIXED"}},
        {"sourceSection": "12.42", "sourceLine": 5, "sourceText": "DL1 segment overview", "constraints": {}}]}}
    evidence = source_evidence(elements, {"element": "4", "section": "13.2"})
    assert len(evidence) == 1 and evidence[0]["sectionMatchedExactly"]
    assert len(evidence[0]["definitions"]) == 1
    assert "13 space" in evidence[0]["definitions"][0]["sourceText"]
    assert source_evidence(elements, {"element": "99", "section": "13.2"}) == []
    assert source_evidence(elements, {"element": "4,99", "section": "12.42"})[0]["sectionMatchedExactly"]
    print("PASS: exact-section source evidence, composite element citations and missing evidence remain explicit")


def write_packet(output_dir, summary, test_rule_reviews, ai_rows_by_test_rule, decision_register):
    output_dir = native(output_dir)
    if output_dir.exists():
        raise ValueError("Refusing to overwrite existing review packet: " + str(output_dir))
    output_dir.mkdir(parents=True)
    pair_path = output_dir / "run4-ai-test-br-semantic-review-pairs.jsonl"
    with pair_path.open("w", encoding="utf-8") as stream:
        for rule_id in sorted(ai_rows_by_test_rule):
            for pair in ai_rows_by_test_rule[rule_id]:
                stream.write(json.dumps(pair, ensure_ascii=True) + "\n")
    with (output_dir / "run4-test-br-semantic-review.csv").open("w", encoding="utf-8-sig", newline="") as stream:
        fields = ["testRuleId", "testRuleTitle", "testRuleSegment", "anchorCandidateCount", "candidateAiBrIds",
                  "reviewStatus", "decision", "reviewer", "rationale", "manualAiCorpusSearchRequired", "noMatchConclusionAllowed"]
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        for item in test_rule_reviews:
            rule = item["testSolutionRequirement"]
            writer.writerow({
                "testRuleId": item["testRuleId"], "testRuleTitle": rule.get("title"),
                "testRuleSegment": (rule.get("sourceAnchor") or {}).get("segment"),
                "anchorCandidateCount": item["anchorCandidateCount"],
                "candidateAiBrIds": ";".join(pair["aiRequirement"]["id"] for pair in item["anchorCandidates"]),
                "reviewStatus": item["reviewStatus"], "decision": "", "reviewer": "", "rationale": "",
                "manualAiCorpusSearchRequired": item["manualAiCorpusSearchRequired"],
                "noMatchConclusionAllowed": False,
            })
    (output_dir / "run4-test-br-semantic-review.jsonl").write_text(
        "".join(json.dumps(item, ensure_ascii=True) + "\n" for item in test_rule_reviews), encoding="utf-8")
    (output_dir / "run4-semantic-review-summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=True), encoding="utf-8")
    (output_dir / "run4-semantic-decision-register.json").write_text(
        json.dumps(decision_register, indent=2, ensure_ascii=True), encoding="utf-8")
    readme = [
        "# Run4 Semantic BR Review Packet", "",
        "This is an evidence packet, not a semantic approval. Every Test Solution rule remains PENDING_SEMANTIC_REVIEW and receives no coverage credit.", "",
        f"Run4 AI BRs included: {summary['aiBrCount']:,} (AI approval filter: none). Independent Test Solution BR denominator: {summary['independentTestSolutionBrCount']:,}.",
        f"Source-anchor candidate pairs: {summary['candidatePairCount']:,}. Independent Test BRs with candidates: {summary['independentTestRulesWithAnchorCandidates']:,}. Independent Test BRs requiring manual corpus search: {summary['independentTestRulesRequiringManualAiCorpusSearch']:,}.",
        "", "## Review sequence", "",
        "1. Start with each `run4-test-br-semantic-review.csv` Test BR row; do not limit review to rows that already have anchor candidates.",
        "2. For candidate rows, compare the full AI statement, candidate Test Rule, cited ATL105 source excerpt, and chain evidence in `run4-ai-test-br-semantic-review-pairs.jsonl`.",
        "3. For rows without anchor candidates, search the complete 5,153-row AI BR chain export by source/context and behavior. Empty candidate lists are not `AI_ONLY` decisions.",
        "4. A named authorized reviewer records one decision with exact ATL105 2026-3 anchor and rationale. `CONFIRMED_MATCH` only when source and business behavior are equivalent; partial/composite/context mismatch stays `REVIEW_REQUIRED` or receives the appropriate allowed disposition.",
        "5. Recompute coverage as distinct independent Test BR IDs with effective confirmed Run4 decisions / eligible independent Test BR denominator. Count a Test BR once even if multiple AI BRs map to it.",
        "", "## Recording a decision", "",
        "Use the append-only Java recorder with the Run4-specific register. Do not edit the seeded register in place. A decision input uses the pair's `reviewId` as `subjectId`, the pair's `matchSegment`, the matched Test Rule's `sourceAnchor`, a named reviewer, rationale, and `matchedTestRuleId` for `CONFIRMED_MATCH`.", "",
        "```powershell", "mvn.cmd exec:java '-Dexec.mainClass=com.coreauth.validator.coverage.RecordSmeDecision' '-Dexec.args=--decision-json path/to/reviewer-decision.json --decision-register specifications/ATL105/test-output/ai-solution-independent-review/2026-10-07-Run4/analysis-v2/run4-semantic-review-v2/run4-semantic-decision-register.json'", "mvn.cmd exec:java '-Dexec.mainClass=com.coreauth.validator.coverage.ValidateSmeDecisionRegister' '-Dexec.args=specifications/ATL105/test-output/ai-solution-independent-review/2026-10-07-Run4/analysis-v2/run4-semantic-review-v2/run4-semantic-decision-register.json'", "```",
        "", "Example decision input (replace placeholders with one pair's exact values; never use a generated/fabricated reviewer identity):", "", "```json", json.dumps({"subjectType": "AI_TO_TEST_CROSSWALK", "subjectId": "<reviewId>", "segment": "<matchSegment>", "decision": "CONFIRMED_MATCH", "reviewer": "<authorized reviewer identity>", "rationale": "<source-backed equivalence rationale>", "sourceAnchor": {"specification": "ATL105", "version": "2026-3", "section": "<test rule section>", "segment": "<test rule segment>", "element": "<test rule element>", "rule": "<test rule source key>"}, "matchedTestRuleId": "<testRuleId>"}, indent=2), "```",
        "", "No reviewer identity, decision, approval, or semantic result has been fabricated. Existing September Run2 decisions were not reused.",
    ]
    (output_dir / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis-directory", type=Path)
    parser.add_argument("--test-solution-directory", type=Path)
    parser.add_argument("--output-directory", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return
    if not all((args.analysis_directory, args.test_solution_directory, args.output_directory)):
        parser.error("--analysis-directory, --test-solution-directory, and --output-directory are required")
    summary, test_rule_reviews, candidate_index, decision_register = build_packet(args.analysis_directory, args.test_solution_directory)
    write_packet(args.output_directory, summary, test_rule_reviews, candidate_index, decision_register)
    print(json.dumps({"output": str(args.output_directory), **summary}, indent=2))


if __name__ == "__main__":
    main()
