package com.coreauth.validator.canonical;
import com.coreauth.validator.validation.ValidationResult;import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;import java.io.IOException;import java.nio.file.Path;import java.util.regex.Pattern;
/** Validates the positional Date and Time Load request and response from ATL105 Section 11.7.3. */
public final class DateTimeLoadPayloadValidator{
 public static final String REQUEST_ROOT="Date and Time Load Request",RESPONSE_ROOT="Date and Time Load Response";private static final String S="DateTimeLoadPayload";private static final Pattern ID=Pattern.compile("^[A-Za-z0-9]{13}$"),DOW=Pattern.compile("^[0-7]$"),DATE=Pattern.compile("^[0-9]{6}$"),TIME=Pattern.compile("^[0-9]{4}$");private final ObjectMapper m;public DateTimeLoadPayloadValidator(){this(new ObjectMapper());}DateTimeLoadPayloadValidator(ObjectMapper m){this.m=m;}
 public ValidationResult validateFile(Path f){ValidationResult r=new ValidationResult(f==null?"date-time-load-payload":f.getFileName().toString());if(f==null){r.addError(S,"AI JSON file is required");return r;}try{v(m.readTree(f.toFile()),r);}catch(IOException e){r.addError(S,"AI JSON is not readable: "+e.getMessage());}return r;}
 public ValidationResult validatePayload(JsonNode p){ValidationResult r=new ValidationResult("date-time-load-payload");v(p,r);return r;}
 private static void v(JsonNode p,ValidationResult r){if(p==null||!p.isObject()){r.addError(S,"AI JSON root must be an object");return;}boolean q=p.path(REQUEST_ROOT).isObject(),s=p.path(RESPONSE_ROOT).isObject();if(q==s){r.addError(S,"AI JSON must contain exactly one Date and Time Load Request or Response root");return;}if(q)req(p.path(REQUEST_ROOT),r);else resp(p.path(RESPONSE_ROOT),r);}
 private static void req(JsonNode n,ValidationResult r){val(n,"InformationByte","?",null,"DT-REQ-001",r);pat(n,"TerminalIdentifier",ID,"13 alphanumeric characters","DT-REQ-002",r);val(n,"LoadType","D",null,"DT-REQ-003",r);}
 private static void resp(JsonNode n,ValidationResult r){val(n,"DataTypeIndicator",":",null,"DT-RESP-001",r);pat(n,"DayOfWeek",DOW,"one numeric day code","DT-RESP-002",r);pat(n,"CurrentDate",DATE,"6 numeric characters","DT-RESP-003",r);pat(n,"CurrentTime",TIME,"4 numeric characters","DT-RESP-004",r);pat(n,"CutTime",TIME,"4 numeric characters","DT-RESP-005",r);pat(n,"Password",Pattern.compile("^[A-Za-z0-9]{6}$"),"6 alphanumeric characters","DT-RESP-006",r);}
 private static void val(JsonNode n,String f,String e,Pattern p,String id,ValidationResult r){if(!e.equals(x(n,f)))r.addError(S,f+" must be "+e+" ("+id+")");}private static void pat(JsonNode n,String f,Pattern p,String d,String id,ValidationResult r){String v=x(n,f);if(v==null||!p.matcher(v).matches())r.addError(S,f+" must be "+d+" ("+id+")");}private static String x(JsonNode n,String f){return n.has(f)&&!n.path(f).isNull()?n.path(f).asText():null;}
}
